---
extends: default
rules:
  comments:
    min-spaces-from-content: 1 # defaults to 2
  document-start: disable # defaults to true wich is annoying and useless 99% of the time
  line-length:
    max: 120 # defaults to 80 which is ... annoying
    allow-non-breakable-words: true
  truthy:
    check-keys: false
ignore:
  api/build
