name: Lint

on: [push, pull_request]

jobs:
  lint-commit:
    name: Lint commit message
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run conform
        uses: siderolabs/conform@v0.1.0-alpha.29
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run mdl
        uses: actionshub/markdownlint@main
