name: Release

on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Init node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Install semantic-release and plugins globally
        run: |
          npm install -g semantic-release
          npm install -g semantic-release-replace-plugin
          npm install -g @semantic-release/exec
          npm install -g @semantic-release/changelog
          npm install -g @semantic-release/git
      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_SECRET }}
          GITHUB_USER: ${{ github.actor }}
